esphome:
  name: shiny-invention
  platform: ESP8266
  board: d1_mini_pro
  includes:
  - PMS_code



wifi:
  # manual_ip:
    # # Set this to the IP of the ESP
    # static_ip: 10.10.10.9
    # # Set this to the IP address of the router. Often ends with .1
    # gateway: 10.10.10.1
    # # The subnet of the network. 255.255.255.0 works for most home networks.
    # subnet: 255.255.255.0

  ssid: !secret esp_wifi_ssid
  password: !secret esp_wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret esp_backup_ssid
    password: !secret esp_backup_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esp_api_password

ota:
  password: !secret esp_ota_password



uart:
  id: uart_bus
  tx_pin: D3
  rx_pin: D4
  baud_rate: 9600

sensor:
  - platform: custom
    lambda: |-
      auto dust_sensor = new PMS5003CustomSensor(id(uart_bus));
      App.register_component(dust_sensor);
      return {dust_sensor->pms5003_PM1_sensor, dust_sensor->pms5003_PM2_5_sensor, dust_sensor->pms5003_PM10_sensor, dust_sensor->pms5003_PB0_3_sensor, dust_sensor->pms5003_PB0_5_sensor, dust_sensor->pms5003_PB1_0_sensor, dust_sensor->pms5003_PB2_5_sensor, dust_sensor->pms5003_PB5_0_sensor, dust_sensor->pms5003_PB10_sensor, dust_sensor->pms5003_UKAQI_sensor};

    sensors:
    - name: "PMS5003 Dust Sensor PM1.0"
      unit_of_measurement: ug/m3
      accuracy_decimals: 0
    - name: "PMS5003 Dust Sensor PM2.5"
      unit_of_measurement: ug/m3
      accuracy_decimals: 0
    - name: "PMS5003 Dust Sensor PM10"
      unit_of_measurement: ug/m3
      accuracy_decimals: 0
    - name: "PMS5003 Dust Sensor PB >0.3um"
      unit_of_measurement: cnt
      accuracy_decimals: 0
    - name: "PMS5003 Dust Sensor PB >0.5um"
      unit_of_measurement: cnt
      accuracy_decimals: 0
    - name: "PMS5003 Dust Sensor PB >1.0um"
      unit_of_measurement: cnt
      accuracy_decimals: 0
    - name: "PMS5003 Dust Sensor PB >2.5um"
      unit_of_measurement: cnt
      accuracy_decimals: 0
    - name: "PMS5003 Dust Sensor PB >5.0um"
      unit_of_measurement: cnt
      accuracy_decimals: 0
    - name: "PMS5003 Dust Sensor PB >10um"
      unit_of_measurement: cnt
      accuracy_decimals: 0
    - name: "PMS5003 Dust Sensor UK AQI"
      unit_of_measurement: rating
      accuracy_decimals: 0